#!/usr/bin/env bash
__fzf_fs_console_edit () 
{ 
    builtin unset -v console_prompt;
    builtin typeset console_prompt="${console[0]##*/}";
    [[ -n "${console[1]}" || "${console[2]}" -eq 0 ]] || { 
        if [[ -n "$KSH_VERSION" ]]; then
            console[1]="$(command fzf --prompt=":${console_prompt} " --print-query <<< "")";
        else
            command tput sc;
            command tput cup 99999 0;
            if [[ -n "$ZSH_VERSION" ]]; then
                builtin vared -p ":${console_prompt} " tmp;
            else
                builtin read -re -p ":${console_prompt} " tmp;
            fi;
            console[1]="$tmp";
            command tput rc;
            command tput ed;
        fi
    };
    builtin set -- ${console[1]};
    (($# > 0)) && { 
        MACRO_FILE="${FZF_FS_CONFIG_DIR}/env/macros" __macro_do "console[1]" "$*"
    };
    builtin eval ${EDITOR} "${console[1]}";
    console[1]=
}
__fzf_fs_console_edit "$@";
builtin unset -f __fzf_fs_console_edit
