#!/usr/bin/env mksh

# fzf-fs-mksh
# part of fzf-fs
# Copyright (C) 2015 D630, The MIT License (MIT)
# <https://github.com/D630/fzf-fs>

# -- DEBUGGING.

#printf '%s (%s)\n' "$BASH_VERSION" "${BASH_VERSINFO[5]}" && exit 0
#set -o errexit
#set -o errtrace
#set -o noexec
#set -o nounset
#set -o pipefail
#set -o verbose
#set -o xtrace
#trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND?")' DEBUG
#exec 2>> ~/fzf-fs.log
#typeset vars_base=$(set -o posix ; set)
#fgrep -v -e "$vars_base" < <(set -o posix ; set) | \
#egrep -v -e "^BASH_REMATCH=" \
#         -e "^OPTIND=" \
#         -e "^REPLY=" \
#         -e "^BASH_LINENO=" \
#         -e "^BASH_SOURCE=" \
#         -e "^FUNCNAME=" | \
#less

# -- FUNCTIONS.

__fzffs_prepare_mksh ()
{
    function __fzffs_clean_sh ()
    {
        builtin :
    };

    function __fzffs_util_echo ()
    {
        IFS=" " builtin print -- "$*"
    };

    function __fzffs_util_echoE ()
    {
        IFS=" " builtin print -r -- "$*"
    };

    function __fzffs_util_echon ()
    {
        IFS=" " builtin print -nr -- "$*"
    }
}

# -- MAIN.

__fzffs_prepare_mksh
