#!/usr/bin/env bash

# fzf-fs
# Copyright (C) 2015 D630, The MIT License (MIT)
# <https://github.com/D630/fzf-fs>

# -- DEBUGGING.

#printf '%s (%s)\n' "$BASH_VERSION" "${BASH_VERSINFO[5]}" && exit 0
#set -o errexit
#set -o errtrace
#set -o noexec
#set -o nounset
#set -o pipefail
#set -o verbose
#set -o xtrace
#trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND?")' DEBUG
#exec 2>> ~/fzf-fs.log
#typeset vars_base=$(set -o posix ; set)
#fgrep -v -e "$vars_base" < <(set -o posix ; set) |
#egrep -v -e "^BASH_REMATCH=" \
#         -e "^OPTIND=" \
#         -e "^REPLY=" \
#         -e "^BASH_LINENO=" \
#         -e "^BASH_SOURCE=" \
#         -e "^FUNCNAME=" |
#less

# -- ALIASES.

{ builtin shopt -s expand_aliases ; } 2> /dev/null

builtin alias array='builtin typeset -a'
builtin alias const='builtin typeset -r'
builtin alias iarray='builtin typeset -ai'
builtin alias int='builtin typeset -i'
builtin alias itable='builtin typeset -Ai'
builtin alias ref='builtin typeset -n'
builtin alias string='builtin typeset +i'
builtin alias table='builtin typeset -A'

# -- MODULES.

FzfFsMain ()
{
    # -- FUNCTIONS.

    function FzfFsMain__get_args ()
    {
        case "$1" in
            "-d" | "--daemon")
                builtin . "${FZF_FS_CONFIG_DIR}/default/src/daemon.sh" && FzfFsDaemon;
                builtin return "$?"
            ;;
            "-h" | "--help")
                builtin . "${FZF_FS_CONFIG_DIR}/default/src/help.sh" && FzfFsHelp;
                builtin return "$?"
            ;;
            "-i" | "--init")
                builtin . fzf-fs-init && FzfFsInit;
                builtin return "$?"
            ;;
            "-v" | "--version")
                builtin . "${FZF_FS_CONFIG_DIR}/default/src/version.sh" && FzfFsVersion;
                builtin return "$?"
            ;;
            *)
                FzfFsMain__run;
                builtin return "$?"
            ;;
        esac;
    };

    function FzfFsMain__get_ls ()
    {
        builtin eval "__ls ${FZF_FS_LS_COMMAND}";
        builtin eval "__ls_color ${FZF_FS_LS_COMMAND_COLOR}"
    };

    function FzfFsMain__init_daemon ()
    {
        if builtin . "${FZF_FS_CONFIG_DIR}/daemon/info"
        then
            exec 9<>"${daemon[0]}";
        else
            { command printf '%s\n' "${source}:Error:83: Could not connect to the daemon with pid: '${daemon[1]}'" 1>&2 ; builtin return 83 ; }
        fi;
    };

    function FzfFsMain__main ()
    {
        builtin unset -v \
            cursor_off \
            cursor_on \
            daemon \
            ret \
            source;

        builtin typeset \
            FZF_FS_CONFIG_DIR="${FZF_FS_CONFIG_DIR:-${XDG_CONFIG_HOME:-${HOME}/.config}/fzf-fs.d}" \
            cursor_on="$(command tput cnorm || command tput ve)" \
            cursor_off="$(command tput civis || command tput vi)" \
            source;

        array daemon;

        builtin typeset -i ret;

        FzfFsMain__prepare_sh 2>/dev/null;
        FzfFsMain__get_args "$@";
        ret="$?"

        #~ if ((ret == 111)); then
            #~ builtin . "${FZF_FS_CONFIG_DIR}/browser/env.cache";
            #~ __fzffs_on_reload;
            #~ __fzffs_main "$PWD";
        #~ else
            #~ __fzffs_cursor 1;
            #~ __fzffs_on_quit;
            #~ #exec 9<&-;
            #~ #exec 9>&-;
            #~ builtin return "$ret";
        #~ fi
    };

    function FzfFsMain__prepare_sh ()
    {
        if [[ -n "$BASH_VERSION" ]]; then
            source="${BASH_SOURCE[0]}";
            builtin . "${FZF_FS_CONFIG_DIR}/default/src/prepare_bash.sh" && FzfFsPrepareBash;
        else
            if [[ -n "$ZSH_VERSION" ]]; then
                source="${(%):-%x}";
                builtin . "${FZF_FS_CONFIG_DIR}/default/src/prepare_zsh.sh" && FzfFsPrepareZsh;
            else
                source="$0";
                [[ -n "$KSH_VERSION" ]] &&
                builtin . "${FZF_FS_CONFIG_DIR}/default/src/prepare_mksh.sh" &&
                FzfFsPrepareMksh;
            fi;
        fi;
    };

    function FzfFsMain__run ()
    {
        if builtin . "${FZF_FS_CONFIG_DIR}/env/env"; then
            if FzfFsMain__source_deps; then
                #~ if FzfFsMain__init_daemon; then
                    builtin . "${FZF_FS_CONFIG_DIR}/default/src/core.sh"
                    FzfFsMain__get_ls;
                    command mkdir -p -m 755 "${FZF_FS_CONFIG_DIR}/browser";
                    __fzffs_dump_env;
                    FzfFsCore FzfFsCore__buffer "$1";
                #~ else
                    #~ builtin return 83
                #~ fi;
            else
                { command printf '%s\n' "${source}:Error:82: Could not source all required modules" 1>&2 ; builtin return 82 ; }
            fi;
        else
            { command printf '%s\n' "${source}:Error:81: Environment file missing" 1>&2 ; builtin return 81 ; }
        fi
    };

    function FzfFsMain__source_deps ()
    {
        builtin . ls-wrapper.sh &&
        builtin . fzf-wrapper.sh &&
        builtin . macro.sh &&
        builtin . spath.sh &&
        builtin . fzf-fs-work-in-progress

    };

    # -- UTILS.

    function FzfFsMain__san ()
    {
        case "$1" in
            -[fn])
                IFS=" " builtin unset ${*}
            ;;
            *)
                IFS=" " builtin unset -v ${*}
        esac
    };

    # -- SOURCE.

    # -- MAIN.

    FzfFsMain__san ret;
    int ret;

    FzfFsMain__main "$@";

    ret="$?";

    # -- POST.

    FzfFsMain__san -f \
        FzfFsMain__get_args \
        FzfFsMain__main \
        FzfFsMain__prepare_sh \
        FzfFsMain__san;

    builtin return "$ret"
}

FzfFsMain "$@"
