#!/usr/bin/env bash
__fzffs_console_cd_up () 
{ 
    console[2]="$*" console_prompt="${console[1]##*/}";
    [[ -n "${console[2]}" || "${console[3]}" -eq 0 ]] || { 
        if [[ -n "$KSH_VERSION" ]]; then
            console[2]="$(command fzf --prompt=":${console_prompt} " --print-query <<< "")";
        else
            command tput sc;
            command tput cup 99999 0;
            if [[ -n "$ZSH_VERSION" ]]; then
                builtin vared -p ":${console_prompt} " tmp;
            else
                builtin read -re -p ":${console_prompt} " tmp;
            fi;
            console[2]="$tmp";
            command tput rc;
            command tput ed;
        fi
    };
    [[ -z "${console[2]//[0-9]/}" ]] && { 
        builtin unset -v s;
        builtin typeset s="$(command printf '%*s' "${console[2]:-1}" "")";
        builtin cd "$(command printf '%s' ${s// /..\/})";
        browser[4]="$PWD"
    }
}
__fzffs_console_cd_up "$@"
builtin unset -f __fzffs_console_cd_up
