#!/usr/bin/env bash
__fzffs_console_console ()
{
    builtin unset -v \
        chars \
        count \
        files \
        selection \
        strings;
    builtin typeset -i count;
    builtin typeset -a \
        chars \
        files \
        selection \
        strings;

    console[3]=1;

    while [[ -n "${console[4]}" ]]
    do
        selection=($(__fzffs_util_select "console" "${files[0]}"));
        if [[ -n "${selection[0]}" && "${selection[1]}" == "ctrl-i" ]]
        then
            files=($(__fzffs_util_ls "console" | command grep -e "^${selection[0]}"))
            if ((${#files[@]} > 1))
            then
                count=0
                strings=(${files[@]#${selection[0]}})
                chars=()
                while [[ -n "${strings[0]}" ]]
                do
                    for i in "${!strings[@]}"
                    do
                        chars[$i]="${strings[$i]:0:1}"
                    done
                    if [[ -z "$(command printf '%s' "${chars[@]//${chars[0]}}")" ]]
                    then
                        count+=1
                        for i in "${!strings[@]}"
                        do
                            strings[$i]="${strings[$i]#${chars[$i]}}"
                        done
                    else
                        strings[0]=
                    fi
                done
                if ((count == 0))
                then
                    files[0]="${selection[0]}"
                    #console pane
                else
                    files[0]=${files[0]:0:$((${#selection[0]} + $count))}
                fi
            else
                files[0]="${files[0]}"
            fi
            builtin continue
        elif [[ "${selection[0]}" == "ctrl-i" ]]
        then
            files[0]=
            #console pane
            builtin continue
        else
            if [[ -n "${selection[0]}" && -n "${selection[1]}" ]]
            then
                console[4]="${selection[1]}";
            else
                console[4]="${selection[0]}";
            fi
            files[0]=
        fi
        console[1]="${FZF_FS_CONFIG_DIR}/console/${console[4]}";
        [[ -f "${console[1]}" ]] && builtin eval . "${console[1]}";
    done;

    console[3]=0
}
__fzffs_console_console "$@"
builtin unset -f __fzffs_console_console
