#!/usr/bin/env bash
__fzffs_console_open_with () 
{ 
    builtin unset -v console_args console_prompt;
    builtin typeset console_args="$*" console_prompt="${console_file##*/}";
    [[ -n "$console_args" ]] || { 
        if [[ -n "$KSH_VERSION" ]]; then
            console_args="$(command fzf --prompt=":${console_prompt} " --print-query <<< "")";
        else
            command tput sc;
            command tput cup 99999 0;
            if [[ -n "$ZSH_VERSION" ]]; then
                builtin vared -p ":${console_prompt} " console_args;
            else
                builtin read -re -p ":${console_prompt} " console_args;
            fi;
            command tput rc;
            command tput ed;
        fi
    };
    builtin set -- ${console_args};
    (($# > 0)) && { 
        __fzffs_util_parse_flags "$*" && builtin shift 1;
        __fzffs_util_parse_macros "$*"
    };
    builtin eval "$(__fzffs_util_echon builtin eval "$console_args")"
}
__fzffs_console_open_with "$@"
builtin unset -f __fzffs_console_open_with
