#!/usr/bin/env bash
__fzffs_console_quit_session () 
{ 
    browser[4]=;
    FZF_FS_BUFFER="quit";
    FZF_FS_BUFFER_OLD="quit";
    builtin break
}
__fzffs_console_quit_session "$@"
builtin unset -f __fzffs_console_quit_session
