#!/usr/bin/env bash
__fzf_fs_keybindings_normal ()
{
    builtin unset -v horiz;
    builtin typeset horiz="$(command printf '%*s' "$((${COLUMNS:-$(command tput cols)} - 4))" '')";
    {
        key="$(command sed -n "/^${1}/ s/^.// p" | command fzf -e +i --no-sort --tac --prompt= --inline-info --expect="$2")"
    }  <<-KEY
${1}key     command
${1}$(command printf '%s\n' "${horiz// /-}")
c1       set/colorscheme_16
cb       set/bg_black_toggle
cc       set/clicolor_force_toggle
cd       set/colorscheme_dark
cl       set/colorscheme_light
cw       set/colorscheme_bw
g-       cd "\$OLDPWD"              "$OLDPWD"
g/       cd /
g1       cd_up 1
g2       cd_up 2
gL       cd /var/log
gM       cd /mnt
gd       cd /dev
ge       cd /etc
gh       cd "\$HOME"                "$HOME"
gl       cd /usr/lib
gm       cd /media
go       cd /opt
gr       cd /
gs       cd /srv
gu       cd /usr
gv       cd /var
g~       cd "\$HOME"                "$HOME"
le       edit "\${file}"            "${file}"
ll       FzfFsCore__enter_file      "${file}"
ln       open_with
lp       page "\${file}"            "${file}"
nd       set/opener_default         "$FZF_FS_OPENER_DEFAULT"
ne       set/opener_editor          "$EDITOR"
ni       set/opener_interactive
np       set/opener_pager           "$PAGER"
qq       quit
q!       quit!
sA       set/sort_atime;            set/sort_reverse_true
sB       set/sort_basename;         set/sort_reverse_false
sC       set/sort_ctime;            set/sort_reverse_true
sM       set/sort_mtime;            set/sort_reverse_false
sS       set/sort_size;             set/sort_reverse_true
sT       set/sort_type;             set/sort_reverse_false
sa       set/sort_atime;            set/sort_reverse_false
sb       set/sort_basename;         set/sort_reverse_true
sc       set/sort_ctime;            set/sort_reverse_false
sm       set/sort_mtime;            set/sort_reverse_true
sr       set/sort_reverse_toggle
ss       set/sort_size;             set/sort_reverse_false
st       set/sort_type;             set/sort_reverse_true
wa       set/show_atime
wc       set/show_ctime
wm       set/show_mtime
zH       set/deference_commandline
zL       set/deference
zc       set/lc_collate_c
zh       set/show_hidden_toggle
zi       set/inline_info_toggle
zl       set/lc_collate_lang        "$LANG"
zm       set/mouse_toggle
zo       set/hscroll_toggle
zs       set/status_bar_on_top_toggle
KEY

}

builtin unset -v c;
builtin typeset -a c;

case "$key" in
    [/?iaoIAO])
        FZF_FS_MODE=search;
        FzfFsCore__show_cursor 1;
        builtin continue
    ;;
    :)
        c='console'
    ;;
    !)
        c='shell'
    ;;
    T)
        c='terminal'
    ;;
    alt-h)
        c='cd_up 2'
    ;;
    ctrl-h)
        c='cd_up 1'
    ;;
    ctrl-l)
        FzfFsCore__enter_file;
        builtin continue
    ;;
    ctrl-r)
        c='reload'
    ;;
    c)
        __fzf_fs_keybindings_normal "$key" "1,b,c,d,l,w";
        case "${key/$'\n'/}" in
            1*)
                c='set/colorscheme_16'
            ;;
            b*)
                c='set/bg_black_toggle'
            ;;
            c*)
                c='set/clicolor_force_toggle'
            ;;
            d*)
                c='set/colorscheme_dark'
            ;;
            l*)
                c='set/colorscheme_light'
            ;;
            w*)
                c='set/colorscheme_bw'
            ;;
        esac
    ;;
    g)
        __fzf_fs_keybindings_normal "$key" "L,M,1,2,r,/,d,e,h,l,m,o,s,u,v,-,~";
        case "${key/$'\n'/}" in
            -*)
                c="cd ${OLDPWD}"
            ;;
            1*)
                c='cd_up 1'
            ;;
            2*)
                c='cd_up 2'
            ;;
            L*)
                c='cd /var/log'
            ;;
            M*)
                c='cd /mnt'
            ;;
            [h~]*)
                c="cd ${HOME}"
            ;;
            [r/]*)
                c='cd /'
            ;;
            d*)
                c='cd /dev'
            ;;
            e*)
                c='cd /etc'
            ;;
            l*)
                c='cd /usr/lib'
            ;;
            m*)
                c='cd /media'
            ;;
            o*)
                c='cd /opt'
            ;;
            s*)
                c='cd /srv'
            ;;
            u*)
                c='cd /usr'
            ;;
            v*)
                c='cd /var'
            ;;
        esac
    ;;
    l)
        __fzf_fs_keybindings_normal "$key" "e,l,p,n";
        case "${key/$'\n'/}" in
            e*)
                c="edit ${file}"
            ;;
            l*)
                FzfFsCore__enter_file;
                builtin continue
            ;;
            p*)
                c="page ${file}"
            ;;
            n*)
                c='open_with'
            ;;
        esac
    ;;
    n)
        __fzf_fs_keybindings_normal "$key" "d,e,i,p";
        case "${key/$'\n'/}" in
            d*)
                c='set/opener_default'
            ;;
            e*)
                c='set/opener_editor'
            ;;
            i*)
                c='set/opener_interactive'
            ;;
            p*)
                c='set/opener_pager'
            ;;
        esac
    ;;
    q)
        __fzf_fs_keybindings_normal "$key" "q,!";
        case "${key/$'\n'/}" in
            !*)
                c='quit!'
            ;;
            q*)
                c='quit'
            ;;
        esac
    ;;
    s)
        __fzf_fs_keybindings_normal "$key" "A,B,C,M,S,T,a,b,c,m,r,s,t";
        case "${key/$'\n'/}" in
            A*)
                c[0]='set/sort_atime';
                c[1]='set/sort_reverse_false'
            ;;
            B*)
                c[0]='set/sort_basename';
                c[1]='set/sort_reverse_false'
            ;;
            C*)
                c[0]='set/sort_ctime';
                c[1]='set/sort_reverse_false'
            ;;
            M*)
                c[0]='set/sort_mtime';
                c[1]='set/sort_reverse_false'
            ;;
            S*)
                c[0]='set/sort_size';
                c[1]='set/sort_reverse_false'
            ;;
            T*)
                c[0]='set/sort_type';
                c[1]='set/sort_reverse_false'
            ;;
            a*)
                c[0]='set/sort_atime';
                c[1]='set/sort_reverse_true'
            ;;
            b*)
                c[0]='set/sort_basename';
                c[1]='set/sort_reverse_true'
            ;;
            c*)
                c[0]='set/sort_ctime';
                c[1]='set/sort_reverse_true'
            ;;
            m*)
                c[0]='set/sort_mtime';
                c[1]='set/sort_reverse_true'
            ;;
            r*)
                c='set/sort_reverse_toggle'
            ;;
            s*)
                c[0]='set/sort_size';
                c[1]='set/sort_reverse_true'
            ;;
            t*)
                c[0]='set/sort_type';
                c[1]='set/sort_reverse_true'
            ;;
        esac
    ;;
    w)
        __fzf_fs_keybindings_normal "$key" "a,c,m";
        case "${key/$'\n'/}" in
            a*)
                c='set/show_atime'
            ;;
            c*)
                c='set/show_ctime'
            ;;
            m*)
                c='set/show_mtime'
            ;;
        esac
    ;;
    z)
        __fzf_fs_keybindings_normal "$key" "H,L,c,h,i,l,m,o,s";
        case "${key/$'\n'/}" in
            H*)
                c='set/deference_commandline'
            ;;
            L*)
                c='set/deference'
            ;;
            c*)
                c='set/lc_collate_c'
            ;;
            h*)
                c='set/show_hidden_toggle'
            ;;
            i*)
                c='set/inline_info_toggle'
            ;;
            l*)
                c='set/lc_collate_lang'
            ;;
            m*)
                c='set/mouse_toggle'
            ;;
            o*)
                c='set/hscroll_toggle'
            ;;
            s*)
                c='set/status_bar_on_top_toggle'
            ;;
        esac
    ;;
esac
